PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX ruian: <http://ruian.linked.opendata.cz/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ec: <http://ec.europa.eu/eurostat/ramon/ontologies/geographic.rdf#>
PREFIX s: <http://schema.org/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE 
{
	?check a s:CheckAction;
		s:location/s:location ?region;
		s:result/s:result [] .
}